
name: gym_app
description: A new Flutter project for a gym system.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.7
  brasil_fields: ^1.5.1
  cached_network_image: ^3.2.3
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  uuid: ^4.5.1
  firebase_auth: ^6.1.0
  mask_text_input_formatter: ^2.4.0
  google_sign_in: ^6.2.1
  flutter_image_compress: ^2.1.0
  supabase_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo_fundo.png
    - assets/google_logo.png
    - assets/logo_nome_fundo.png