
name: gym_app
description: A new Flutter project for a gym system.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  app_links: 6.3.2   
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.7
  brasil_fields: ^1.5.1
  uuid: ^4.5.1
  mask_text_input_formatter: ^2.4.0
  image: ^4.1.7 # Para processamento de imagem
  flutter_image_compress: ^2.3.0 # Versão unificada
  google_maps_flutter: ^2.6.0
  geolocator: ^13.0.2

  # Cache e Imagens de Rede
  cached_network_image: ^3.3.1 # Versão estável recente

  # Autenticação e Banco de Dados (Versões Atualizadas para evitar conflitos)
  firebase_core: ^4.1.1 # Sugiro conferir a versão mais recente compatível com seu ambiente
  cloud_firestore: ^6.0.2 # Sugiro conferir a versão mais recente compatível com seu ambiente
  firebase_storage: ^13.0.2 # Sugiro conferir a versão mais recente compatível com seu ambiente
  firebase_auth: ^6.1.0 # Sugiro conferir a versão mais recente compatível com seu ambiente
  google_sign_in: ^6.2.1
  supabase_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo_fundo.png
    - assets/google_logo.png
    - assets/logo_nome_fundo.png